name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install MPI & NetCDF
      run: |
        sudo apt-get update
        sudo apt-get install -y openmpi-bin libopenmpi-dev libhdf5-mpi-dev libpnetcdf-dev libnetcdf-pnetcdf-dev ffmpeg

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build requirements
      run: |
        sudo apt-get install git
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools setuptools_scm coverage build pytest

    - name: Install GaPFlow
      run: |
        python -m pip install mpi4py
        pip install -v --force-reinstall --no-cache --no-binary muGrid muGrid
        pip install --upgrade-strategy only-if-needed .[test]

    - name: Test with pytest
      run: |
        coverage run
        bash maintenance/update_coverage_badge.sh

    - name: Upload coverage badge
      if: matrix.python-version == '3.12' && github.ref == 'refs/heads/main'
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_SECRET }}
        gist_id: fac7fa61e1899b1e74b3bab598fe6513
        file_path: badge.svg

  # deploy:
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
  #   needs: test
  #   environment:
  #     name: release
  #   permissions:
  #     # IMPORTANT: this permission is mandatory for trusted publishing
  #     id-token: write

  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install setuptools wheel twine build

  #     - name: Package dist
  #       run: |
  #         python3 -m build

  #     - name: Publish package on PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
